package historical_migrations

import historical_models "github.com/anan112pcmec/Burung-backend-2/watcher_app/database/hystorical_db/models"

var model_list []interface{} = []interface{}{
	historical_models.BarangInduk{},
	historical_models.KategoriBarang{},
	historical_models.VarianBarang{},
	historical_models.EntitySocialMedia{},

	historical_models.Komentar{},
	historical_models.KomentarChild{},
	historical_models.Keranjang{},
	historical_models.BarangDisukai{},
	historical_models.BarangWishlist{},
	historical_models.AlamatPengguna{},
	historical_models.Wishlist{},
	historical_models.Review{},
	historical_models.ReviewLike{},
	historical_models.ReviewDislike{},
	historical_models.Jenis_Seller{},
	historical_models.BatalTransaksi{},
	historical_models.Follower{},
	historical_models.AlamatGudang{},
	historical_models.DistributorData{},
	historical_models.BrandData{},
	historical_models.Etalase{},
	historical_models.BarangKeEtalase{},
	historical_models.DiskonProduk{},
	historical_models.BarangDiDiskon{},
	historical_models.InformasiKurir{},
	historical_models.InformasiKendaraanKurir{},
	historical_models.AlamatKurir{},
	historical_models.BidKurirData{},
	historical_models.BidKurirNonEksScheduler{},
	historical_models.BidKurirEksScheduler{},

	historical_models.Pengguna{},
	historical_models.Seller{},
	historical_models.Kurir{},

	historical_models.MediaPenggunaProfilFoto{},
	historical_models.MediaSellerProfilFoto{},
	historical_models.MediaSellerBannerFoto{},
	historical_models.MediaSellerTokoFisikFoto{},
	historical_models.MediaKurirProfilFoto{},
	historical_models.MediaEtalaseFoto{},
	historical_models.MediaBarangIndukFoto{},
	historical_models.MediaBarangIndukVideo{},
	historical_models.MediaKategoriBarangFoto{},
	historical_models.MediaDistributorDataDokumen{},
	historical_models.MediaDistributorDataNPWPFoto{},
	historical_models.MediaDistributorDataNIBFoto{},
	historical_models.MediaDistributorDataSuratKerjasamaDokumen{},
	historical_models.MediaBrandDataPerwakilanDokumen{},
	historical_models.MediaBrandDataSertifikatFoto{},
	historical_models.MediaBrandDataNIBFoto{},
	historical_models.MediaBrandDataNPWPFoto{},
	historical_models.MediaBrandDataLogoFoto{},
	historical_models.MediaBrandDataSuratKerjasamaDokumen{},
	historical_models.MediaInformasiKendaraanKurirKendaraanFoto{},
	historical_models.MediaInformasiKendaraanKurirBPKBFoto{},
	historical_models.MediaInformasiKendaraanKurirSTNKFoto{},
	historical_models.MediaInformasiKurirKTPFoto{},
	historical_models.MediaReviewFoto{},
	historical_models.MediaReviewVideo{},
	historical_models.MediaTransaksiApprovedFoto{},
	historical_models.MediaTransaksiApprovedVideo{},
	historical_models.MediaPengirimanPickedUpFoto{},
	historical_models.MediaPengirimanSampaiFoto{},
	historical_models.MediaPengirimanEkspedisiPickedUpFoto{},
	historical_models.MediaPengirimanEkspedisiSampaiAgentFoto{},

	historical_models.PayOutKurir{},
	historical_models.PayOutSeller{},

	historical_models.Pengiriman{},
	historical_models.JejakPengiriman{},
	historical_models.PengirimanEkspedisi{},
	historical_models.JejakPengirimanEkspedisi{},

	historical_models.RekeningSeller{},
	historical_models.RekeningKurir{},

	historical_models.Pembayaran{},
	historical_models.Transaksi{},
	historical_models.TransaksiFailed{},
}
