package historical_migrations

import cass_models "github.com/anan112pcmec/Burung-backend-2/watcher_app/database/cassandra/models"

var model_list []interface{} = []interface{}{
	cass_models.BarangInduk{},
	cass_models.KategoriBarang{},
	cass_models.VarianBarang{},
	cass_models.EntitySocialMedia{},

	cass_models.Komentar{},
	cass_models.KomentarChild{},
	cass_models.Keranjang{},
	cass_models.BarangDisukai{},
	cass_models.BarangWishlist{},
	cass_models.AlamatPengguna{},
	cass_models.Wishlist{},
	cass_models.Review{},
	cass_models.ReviewLike{},
	cass_models.ReviewDislike{},
	cass_models.Jenis_Seller{},
	cass_models.BatalTransaksi{},
	cass_models.Follower{},
	cass_models.AlamatGudang{},
	cass_models.DistributorData{},
	cass_models.BrandData{},
	cass_models.Etalase{},
	cass_models.BarangKeEtalase{},
	cass_models.DiskonProduk{},
	cass_models.BarangDiDiskon{},
	cass_models.InformasiKurir{},
	cass_models.InformasiKendaraanKurir{},
	cass_models.AlamatKurir{},
	cass_models.BidKurirData{},
	cass_models.BidKurirNonEksScheduler{},
	cass_models.BidKurirEksScheduler{},

	cass_models.Pengguna{},
	cass_models.Seller{},
	cass_models.Kurir{},

	cass_models.MediaPenggunaProfilFoto{},
	cass_models.MediaSellerProfilFoto{},
	cass_models.MediaSellerBannerFoto{},
	cass_models.MediaSellerTokoFisikFoto{},
	cass_models.MediaKurirProfilFoto{},
	cass_models.MediaEtalaseFoto{},
	cass_models.MediaBarangIndukFoto{},
	cass_models.MediaBarangIndukVideo{},
	cass_models.MediaKategoriBarangFoto{},
	cass_models.MediaDistributorDataDokumen{},
	cass_models.MediaDistributorDataNPWPFoto{},
	cass_models.MediaDistributorDataNIBFoto{},
	cass_models.MediaDistributorDataSuratKerjasamaDokumen{},
	cass_models.MediaBrandDataPerwakilanDokumen{},
	cass_models.MediaBrandDataSertifikatFoto{},
	cass_models.MediaBrandDataNIBFoto{},
	cass_models.MediaBrandDataNPWPFoto{},
	cass_models.MediaBrandDataLogoFoto{},
	cass_models.MediaBrandDataSuratKerjasamaDokumen{},
	cass_models.MediaInformasiKendaraanKurirKendaraanFoto{},
	cass_models.MediaInformasiKendaraanKurirBPKBFoto{},
	cass_models.MediaInformasiKendaraanKurirSTNKFoto{},
	cass_models.MediaInformasiKurirKTPFoto{},
	cass_models.MediaReviewFoto{},
	cass_models.MediaReviewVideo{},
	cass_models.MediaTransaksiApprovedFoto{},
	cass_models.MediaTransaksiApprovedVideo{},
	cass_models.MediaPengirimanPickedUpFoto{},
	cass_models.MediaPengirimanSampaiFoto{},
	cass_models.MediaPengirimanEkspedisiPickedUpFoto{},
	cass_models.MediaPengirimanEkspedisiSampaiAgentFoto{},

	cass_models.PayOutKurir{},
	cass_models.PayOutSeller{},

	cass_models.Pengiriman{},
	cass_models.JejakPengiriman{},
	cass_models.PengirimanEkspedisi{},
	cass_models.JejakPengirimanEkspedisi{},

	cass_models.RekeningSeller{},
	cass_models.RekeningKurir{},

	cass_models.Pembayaran{},
	cass_models.Transaksi{},
	cass_models.TransaksiFailed{},
}
